---
  - name: Synchronize list home directories
    ansible.posix.synchronize:
      src: "/Volumes/Users/{{ ansible_user }}/{{ item.src }}"
      dest: "rsync://{{ ansible_host }}/Users/{{ ansible_user }}/{{ item.dest | default('', true) }}"
      recursive: true
    loop: "{{ sync_dirs }}" 