---
#  - name: Synchronize list home directories
#    ansible.posix.synchronize:
#      mode: push
#      src: "/Users/{{ ansible_user }}/{{ item.src }}"
#      dest: "/Users/{{ ansible_user }}/"
#      recursive: true
#      archive: true
#      delay_updates: true
#    loop: "{{ sync_dirs }}" 

  - name: Copy user files and directories
    ansible.posix.synchronize:
      src: "/Users/{{ ansible_user }}/{{ item.src }}"
      dest: "/Users/{{ ansible_user }}/{{ item.parent }}"
      recursive: "{{ item.recurse }}" 
      force: "{{ item.overwrite }}"
      mode: "push"
      owner: true
      delay_updates: true
      archive: true
    become: true
    when: "{{ item.xfer }}"
    loop: "{{ sync_user }}"
